timing: True
debug: False
stop_at_error: False

likelihood:
  lsst_y1.lsst_3x2pt:
    path: ./external_modules/data/lsst_y1
    data_file: LSST_Y1_no_scale_cut.dataset
    print_datavector: False
    non_linear_emul: 1
    kmax_boltzmann: 5.0

params:
  logA:
    prior:
      min: 2.84
      max: 3.21
    ref:
      dist: norm
      loc: 3.045
      scale: 0.05
    proposal: 0.05
    latex: \log(10^{10} A_\mathrm{s})
    drop: true
  As:
    value: 'lambda logA: 1e-10*np.exp(logA)'
    latex: A_\mathrm{s}
  ns:
    prior:
      min: 0.92
      max: 1.00
    ref:
      dist: norm
      loc: 0.9649
      scale: 0.01
    proposal: 0.01
    latex: n_\mathrm{s}
  H0:
    prior:
      min: 61
      max: 73
    ref:
      dist: norm
      loc: 67.32
      scale: 3
    proposal: 3
    latex: H_0
  omegab:
    prior:
      min: 0.04
      max: 0.06
    ref:
      dist: norm
      loc: 0.0493382322
      scale: 0.003
    proposal: 0.003
    latex: \Omega_\mathrm{b}
    drop: true
  omegam:
    prior:
      min: 0.24
      max: 0.4
    ref:
      dist: norm
      loc: 0.3166
      scale: 0.02
    proposal: 0.02
    latex: \Omega_\mathrm{m}
    drop: true
  mnu:
    value: 0.06
  tau:
    value: 0.05
    latex: \tau_\mathrm{reio}
  omegal:
    latex: \Omega_\Lambda
  omegamh2:
    derived: 'lambda omegam, H0: omegam*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  omegabh2:
    value: 'lambda omegab, H0: omegab*(H0/100)**2'
    latex: \Omega_\mathrm{b} h^2
  omegach2:
    value: 'lambda omegam, omegab, mnu, H0: (omegam-omegab)*(H0/100)**2-(mnu*(3.046/3)**0.75)/94.0708'
    latex: \Omega_\mathrm{c} h^2
  omegan2:
    latex: \Omega_\mathrm{\\nu} h^2
  omegan:
    derived: 'lambda omegan2, H0: omegan2/((H0/100)**2)'
    latex: \Omega_\mathrm{\\nu}
  sigma8:
    latex: \sigma_8
  s8h5:
    derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
    latex: \sigma_8/h^{0.5}
  s8omegamp5:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.5'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
  s8omegamp25:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.25'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
  sigma8:
    latex: \sigma_8
  LSST_BARYON_Q1:
    value: 0.0
    latex: Q1_\mathrm{LSST}^1
  LSST_BARYON_Q2:
    value: 0.0
    latex: Q2_\mathrm{LSST}^2
  w:
    value: -1
    latex: w0
  w_growth:
    value: -1
    latex: w_\mathrm{growth}
  omegam_growth:
    prior:
      min: 0.24
      max: 0.4
    ref:
      dist: norm
      loc: 0.3166
      scale: 0.02
    proposal: 0.02
    latex: \Omega_\mathrm{m}^\mathrm{growth}
  #Galaxy bias, shear calibration, baryons do not enter emulation
  LSST_DZ_S1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^1
  LSST_DZ_S2:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^2
  LSST_DZ_S3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^3
  LSST_DZ_S4:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^4
  LSST_DZ_S5:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^5
  LSST_A1_1:
    prior:
      min: -5
      max:  5
    ref:
      dist: norm
      loc: 0.5
      scale: 0.1
    proposal: 0.5
    latex: A_\mathrm{1-IA,LSST}^1
  LSST_A1_2:
    prior:
      min: -5
      max:  5
    ref:
      dist: norm
      loc: 0.
      scale: 0.1
    proposal: 0.5
    latex: A_\mathrm{1-IA,LSST}^2
  LSST_A1_3:
    value: 0
    latex: A_\mathrm{1-IA,LSST}^3
  LSST_A1_4:
    value: 0
    latex: A_\mathrm{1-IA,LSST}^4
  LSST_A1_5:
    value: 0
    latex: A_\mathrm{1-IA,LSST}^5
  LSST_A2_1:
    value: 0.0
    latex: A_\mathrm{2-IA,LSST}^1
  LSST_A2_2:
    value: 0.0
    latex: A_\mathrm{2-IA,LSST}^2
  LSST_A2_3:
    value: 0
    latex: A_\mathrm{2-IA,LSST}^3
  LSST_A2_4:
    value: 0
    latex: A_\mathrm{2-IA,LSST}^4
  LSST_A2_5:
    value: 0
    latex: A_\mathrm{2-IA,LSST}^5
  LSST_BTA_1:
    value: 0.0
    latex: A_\mathrm{BTA-IA,LSST}^1
  LSST_BTA_2:
    value: 0
    latex: A_\mathrm{BTA-IA,LSST}^2
  LSST_BTA_3:
    value: 0
    latex: A_\mathrm{BTA-IA,LSST}^3
  LSST_BTA_4:
    value: 0
    latex: A_\mathrm{BTA-IA,LSST}^4
  LSST_BTA_5:
    value: 0
    latex: A_\mathrm{BTA-IA,LSST}^5
  #shear calibration need to be set to 0 for training emulators
  LSST_M1:
    value: 0.0
    latex: m_\mathrm{LSST}^1
  LSST_M2:
    value: 0.0
    latex: m_\mathrm{LSST}^2
  LSST_M3:
    value: 0.0
    latex: m_\mathrm{LSST}^3
  LSST_M4:
    value: 0.0
    latex: m_\mathrm{LSST}^4
  LSST_M5:
    value: 0.0
    latex: m_\mathrm{LSST}^5
  LSST_BARYON_Q1:
    value: 0.0
    latex: Q1_\mathrm{LSST}^1
  LSST_BARYON_Q2:
    value: 0.0
    latex: Q2_\mathrm{LSST}^2
  LSST_BARYON_Q3:
    value: 0.0
    latex: Q3_\mathrm{LSST}^3
  LSST_BARYON_Q4:
    value: 0.0
    latex: Q4_\mathrm{LSST}^4
# Lensing photo-z errors
  LSST_DZ_L1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{l,LSST}^1
  LSST_DZ_L2:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{l,LSST}^2
  LSST_DZ_L3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{l,LSST}^3
  LSST_DZ_L4:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{l,LSST}^4
  LSST_DZ_L5:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.005
    ref:
      dist: norm
      loc: 0.0
      scale: 0.005
    proposal: 0.005
    latex: \Delta z_\mathrm{l,LSST}^5
  # Point Mass parameters; use for training for now
  LSST_PM1:
    value: 0.0
    # prior:
    #   min: -5
    #   max: 5
    # ref:
    #   dist: norm
    #   loc: 0.0
    #   scale: 0.5
    # proposal: 0.5
    latex: PM_\mathrm{LSST}^1
  LSST_PM2:
    value: 0.0
    # prior:
    #   min: -5
    #   max: 5
    # ref:
    #   dist: norm
    #   loc: 0.0
    #   scale: 0.5
    # proposal: 0.5
    latex: PM_\mathrm{LSST}^2
  LSST_PM3:
    value: 0.0
    # prior:
    #   min: -5
    #   max: 5
    # ref:
    #   dist: norm
    #   loc: 0.0
    #   scale: 0.5
    # proposal: 0.5
    latex: PM_\mathrm{LSST}^3
  LSST_PM4:
    value: 0.0
    # prior:
    #   min: -5
    #   max: 5
    # ref:
    #   dist: norm
    #   loc: 0.0
    #   scale: 0.5
    # proposal: 0.5
    latex: PM_\mathrm{LSST}^4
  LSST_PM5:
    value: 0.0
    # prior:
    #   min: -5
    #   max: 5
    # ref:
    #   dist: norm
    #   loc: 0.0
    #   scale: 0.5
    # proposal: 0.5
    latex: PM_\mathrm{LSST}^5
  # galaxy bias parameters set to some fiducial value for training emulators
  LSST_B1_1:
    value: 1.24
    latex: b_\mathrm{1-LSST}^1
  LSST_B1_2:
    value: 1.36
    latex: b_\mathrm{1-LSST}^2
  LSST_B1_3:
    value: 1.47
    latex: b_\mathrm{1-LSST}^3
  LSST_B1_4:
    value: 1.60
    latex: b_\mathrm{1-LSST}^4
  LSST_B1_5:
    value: 1.76
    latex: b_\mathrm{1-LSST}^5
  ###TEST of training with galaxy bias
  # LSST_B1_1:
  #   prior:
  #     min: 0.8
  #     max: 3
  #   ref:
  #     dist: norm
  #     loc: 1.24
  #     scale: 0.15
  #   proposal: 0.1
  #   latex: b_\mathrm{1-LSST}^1
  # LSST_B1_2:
  #   prior:
  #     min: 0.8
  #     max: 3
  #   ref:
  #     dist: norm
  #     loc: 1.36
  #     scale: 0.15
  #   proposal: 0.1
  #   latex: b_\mathrm{1-LSST}^2
  # LSST_B1_3:
  #   prior:
  #     min: 0.8
  #     max: 3
  #   ref:
  #     dist: norm
  #     loc: 1.47
  #     scale: 0.15
  #   proposal: 0.1
  #   latex: b_\mathrm{1-LSST}^3
  # LSST_B1_4:
  #   prior:
  #     min: 0.8
  #     max: 3
  #   ref:
  #     dist: norm
  #     loc: 1.60
  #     scale: 0.15
  #   proposal: 0.1
  #   latex: b_\mathrm{1-LSST}^4
  # LSST_B1_5:
  #   prior:
  #     min: 0.8
  #     max: 3
  #   ref:
  #     dist: norm
  #     loc: 1.76
  #     scale: 0.1
  #   proposal: 0.1
  #   latex: b_\mathrm{1-LSST}^5

theory:
  camb:
    path: ./external_modules/code/CAMB
    stop_at_error: False
    use_renames: True
    extra_args:
      halofit_version: takahashi
      AccuracyBoost: 1.15
      lens_potential_accuracy: 1.0
      num_massive_neutrinos: 1
      nnu: 3.046
      dark_energy_model: ppf
      accurate_massive_neutrino_transfers: false
      k_per_logint: 20

emulator:
  io:
      #savedir: ./projects/lsst_y1/emulator_output_3x2/lhs/dvs_for_training_1M 
      #savedir: ./projects/lsst_y1/emulator_output_3x2/random/dvs_for_training_4M    
      #savedir: ./projects/lsst_y1/emulator_output_3x2_with_galaxy_bias/lhs/dvs_for_training_10k  
      savedir: ./projects/lsst_y1/emulator_output_3x2 
      save_train_data: true             
      save_intermediate_model: true
  training:
      dv_fid: ./projects/lsst_y1/data/example3_lsst_y1_theory.modelvector
      chi_sq_cut: 8e+4
      n_train_iter: 1
      n_lhs: 1000000 
      n_resample: 9600
      #n_resample: 96 #KZ debug
      emu_type: nn
      batch_size: 32
      n_epochs: 100
  #shear calib and galaxy bias information is only used when sampling, since they're not considered in training
  shear_calib:
      mask: ./projects/lsst_y1/data/emu_files/shear_calib_mask.npy
      prior_std: 0.005, 0.005, 0.005, 0.005, 0.005
  galaxy_bias:
      mask: ./projects/lsst_y1/data/emu_files/bias_mask.npy
      bias_fid: 1.24, 1.36, 1.47, 1.60, 1.76
  baryons:
      n_pcas_baryon: 0
      prior_Q1: -3., 12.
  sampling:
      scalecut_mask: ./projects/lsst_y1/data/lsst_3x2.mask
      #sampling here doesn't matter if n_train_iter=1, but still save here for comparison
      n_mcmc: 10000
      #n_mcmc: 10 #KZ debug
      n_emcee_walkers: 120
      n_burn_in: 5000
      #n_burn_in: 0 #KZ debug
      n_thin: 5
      #n_thin: 1 #KZ debug
      temper0: 0.05 #THIS has full control now, no increment, no minimum
      temper_increment: 0.1
  probe: '3x2pt'


output: ./projects/lsst_y1/chains/generate_dv_emu_1